apiVersion: v1
kind: Service
metadata:
  name: jenkins-server
  namespace: ci-cd
  labels:
    app: jenkins-server
spec:
  selector:
    app: jenkins-server
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: it
      port: 50000
      targetPort: 50000
